name: cs573
channels:
  - pytorch
dependencies:
  - python=3.12
  - jupyter
  - numpy < 2
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - pillow
  - tqdm
  - tensorboard
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
